version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    parameters:
      $CIRCLE_WORKFLOW_ID:
        type: string
        default: "Hello World"
    steps:
      - run: echo << $CIRCLE_WORKFLOW_ID >>
